[package]
name = "oxide-backend-metal"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
oxide-core.workspace = true
oxide-alloc.workspace = true
oxide-quant.workspace = true
bytemuck.workspace = true
thiserror.workspace = true
tracing.workspace = true
