#![allow(
    clippy::unreadable_literal,
    clippy::too_many_lines,
    clippy::manual_find
)]

use oxide_core::hardware::HardwareFormFactor;
use serde::{Deserialize, Serialize};

/// Foundational and Specialized Model Families supported by Oxide Engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ModelFamily {
    // Foundational Text & Code
    Qwen,
    DeepSeek,
    Llama,
    Kimi,
    Glm,
    Gemma,
    Mistral,

    // Multimodal Vision, Audio & Video
    Whisper,
    Parakeet,
    Kokoro,
    Chatterbox,
    StableDiffusion,
    Flux,
    Wan,
    HunyuanVideo,
    NemotronOmni,
    Lance,
    QwenOmni,
    InternVl,
    Llava,

    // Specialized & Niche
    QwenEmbedding,
    BgeM3,
    NomicEmbed,
    IsaacGr00t,
    KairosWorldModel,
    OpenTslm,
    ChatTs,
    EsmBio,
    SgsTheoremProver,
    StrandsDecider,
    Clef,
    Trellis3D,
    Cube3D,
    KronosTrading,
}

/// Modality and Task Type for Model Inference & Serving.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ModelModality {
    TextOnly,
    CodeReasoning,
    VisionLanguage,
    TextToImage,
    TextToVideo,
    SpeechToTextAsr,
    TextToSpeechTts,
    OmniAnyToAny,
    EmbeddingVector,
    RoboticsActionVla,
    WorldModelSimulation,
    TimeSeriesTabular,
    ScientificBioMath,
    DecisionAgentic,
    Asset3DGeneration,
    FinancialTradingTimeSeries,
}

/// Core Model Architecture Class.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ModelArchitectureType {
    DenseTransformer,
    MixtureOfExpertsMoe,
    MultiHeadLatentAttentionMla,
    DiffusionTransformerDiT,
    HybridLinearAttention,
    ConvTransformerAsr,
    NeuralAudioVocoderTts,
    VlaActionTransformer,
    WorldModelPredictor,
    DecisionEngine,
    FinancialCausalTransformer,
}

/// Quantization and Weights Precision Class.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum QuantizationClass {
    Nvfp4Blackwell,
    Ptq1_0Ternary,
    GgufQ4KM,
    GgufQ8_0,
    Fp8E4M3,
    Int8Uniform,
    Bf16Precision,
    Fp16Precision,
}

/// Complete Structural Specification for Supported Open-Weight Models.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ModelSpecification {
    pub name: &'static str,
    pub identifier: &'static str,
    pub family: ModelFamily,
    pub modality: ModelModality,
    pub architecture: ModelArchitectureType,
    pub default_quantization: QuantizationClass,
    pub total_parameters_billion: f32,
    pub active_parameters_billion: f32,
    pub hidden_dim: u32,
    pub intermediate_dim: u32,
    pub num_layers: u32,
    pub num_heads: u32,
    pub num_kv_heads: u32,
    pub head_dim: u32,
    pub vocab_size: u32,
    pub max_context_tokens: u32,
    pub rope_theta: f32,
    pub supports_nvfp4: bool,
    pub optimal_form_factor: HardwareFormFactor,
}

impl ModelSpecification {
    /// Discovers model specification from model query string.
    #[must_use]
    pub fn lookup(query: &str) -> Option<Self> {
        let q = query.to_lowercase();
        let models = Self::catalog();

        for m in models {
            if q.contains(m.identifier) || q.contains(&m.name.to_lowercase()) {
                return Some(m);
            }
        }
        None
    }

    /// Full Catalog of foundational, multimodal, MoE, and specialized models.
    #[must_use]
    pub fn catalog() -> Vec<Self> {
        vec![
            // ----------------------------------------------------
            // 1. Foundational Text & Code Models (General & MoE)
            // ----------------------------------------------------
            Self {
                name: "Qwen 3.8",
                identifier: "qwen-3.8",
                family: ModelFamily::Qwen,
                modality: ModelModality::TextOnly,
                architecture: ModelArchitectureType::DenseTransformer,
                default_quantization: QuantizationClass::GgufQ4KM,
                total_parameters_billion: 3.8,
                active_parameters_billion: 3.8,
                hidden_dim: 2560,
                intermediate_dim: 9728,
                num_layers: 32,
                num_heads: 20,
                num_kv_heads: 4,
                head_dim: 128,
                vocab_size: 152064,
                max_context_tokens: 32768,
                rope_theta: 1000000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::DesktopWorkstation,
            },
            Self {
                name: "DeepSeek V4 (MoE)",
                identifier: "deepseek-v4",
                family: ModelFamily::DeepSeek,
                modality: ModelModality::TextOnly,
                architecture: ModelArchitectureType::MultiHeadLatentAttentionMla,
                default_quantization: QuantizationClass::Nvfp4Blackwell,
                total_parameters_billion: 236.0,
                active_parameters_billion: 21.0,
                hidden_dim: 7168,
                intermediate_dim: 18432,
                num_layers: 61,
                num_heads: 128,
                num_kv_heads: 128,
                head_dim: 128,
                vocab_size: 102400,
                max_context_tokens: 131072,
                rope_theta: 10000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::EnterpriseRackServer,
            },
            Self {
                name: "DeepSeek-R1 (Reasoning)",
                identifier: "deepseek-r1",
                family: ModelFamily::DeepSeek,
                modality: ModelModality::CodeReasoning,
                architecture: ModelArchitectureType::MultiHeadLatentAttentionMla,
                default_quantization: QuantizationClass::Nvfp4Blackwell,
                total_parameters_billion: 671.0,
                active_parameters_billion: 37.0,
                hidden_dim: 7168,
                intermediate_dim: 18432,
                num_layers: 61,
                num_heads: 128,
                num_kv_heads: 128,
                head_dim: 128,
                vocab_size: 129280,
                max_context_tokens: 131072,
                rope_theta: 10000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::EnterpriseRackServer,
            },
            Self {
                name: "Kimi K3 (Long-Context MoE)",
                identifier: "kimi-k3",
                family: ModelFamily::Kimi,
                modality: ModelModality::TextOnly,
                architecture: ModelArchitectureType::MixtureOfExpertsMoe,
                default_quantization: QuantizationClass::Nvfp4Blackwell,
                total_parameters_billion: 180.0,
                active_parameters_billion: 16.0,
                hidden_dim: 6144,
                intermediate_dim: 16384,
                num_layers: 48,
                num_heads: 64,
                num_kv_heads: 8,
                head_dim: 128,
                vocab_size: 151936,
                max_context_tokens: 1048576, // 1M context
                rope_theta: 5000000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::EnterpriseRackServer,
            },
            Self {
                name: "GLM-5.3",
                identifier: "glm-5.3",
                family: ModelFamily::Glm,
                modality: ModelModality::TextOnly,
                architecture: ModelArchitectureType::DenseTransformer,
                default_quantization: QuantizationClass::GgufQ4KM,
                total_parameters_billion: 9.0,
                active_parameters_billion: 9.0,
                hidden_dim: 4096,
                intermediate_dim: 13696,
                num_layers: 40,
                num_heads: 32,
                num_kv_heads: 2,
                head_dim: 128,
                vocab_size: 151552,
                max_context_tokens: 131072,
                rope_theta: 1000000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::DesktopWorkstation,
            },
            Self {
                name: "Llama 4",
                identifier: "llama-4",
                family: ModelFamily::Llama,
                modality: ModelModality::TextOnly,
                architecture: ModelArchitectureType::MixtureOfExpertsMoe,
                default_quantization: QuantizationClass::Nvfp4Blackwell,
                total_parameters_billion: 110.0,
                active_parameters_billion: 12.0,
                hidden_dim: 5120,
                intermediate_dim: 14336,
                num_layers: 48,
                num_heads: 40,
                num_kv_heads: 8,
                head_dim: 128,
                vocab_size: 128256,
                max_context_tokens: 131072,
                rope_theta: 500000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::EnterpriseRackServer,
            },
            Self {
                name: "Qwen3-Coder",
                identifier: "qwen3-coder",
                family: ModelFamily::Qwen,
                modality: ModelModality::CodeReasoning,
                architecture: ModelArchitectureType::DenseTransformer,
                default_quantization: QuantizationClass::GgufQ4KM,
                total_parameters_billion: 14.0,
                active_parameters_billion: 14.0,
                hidden_dim: 5120,
                intermediate_dim: 13824,
                num_layers: 48,
                num_heads: 40,
                num_kv_heads: 8,
                head_dim: 128,
                vocab_size: 152064,
                max_context_tokens: 131072,
                rope_theta: 1000000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::DesktopWorkstation,
            },
            // ----------------------------------------------------
            // 2. Multimodal Models (VLMs, Diffusion, Audio, Omni)
            // ----------------------------------------------------
            Self {
                name: "Qwen3-VL",
                identifier: "qwen3-vl",
                family: ModelFamily::Qwen,
                modality: ModelModality::VisionLanguage,
                architecture: ModelArchitectureType::DenseTransformer,
                default_quantization: QuantizationClass::GgufQ4KM,
                total_parameters_billion: 8.0,
                active_parameters_billion: 8.0,
                hidden_dim: 4096,
                intermediate_dim: 11008,
                num_layers: 36,
                num_heads: 32,
                num_kv_heads: 4,
                head_dim: 128,
                vocab_size: 152064,
                max_context_tokens: 32768,
                rope_theta: 1000000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::DesktopWorkstation,
            },
            Self {
                name: "InternVL",
                identifier: "internvl",
                family: ModelFamily::InternVl,
                modality: ModelModality::VisionLanguage,
                architecture: ModelArchitectureType::DenseTransformer,
                default_quantization: QuantizationClass::GgufQ4KM,
                total_parameters_billion: 8.0,
                active_parameters_billion: 8.0,
                hidden_dim: 4096,
                intermediate_dim: 11008,
                num_layers: 32,
                num_heads: 32,
                num_kv_heads: 8,
                head_dim: 128,
                vocab_size: 151936,
                max_context_tokens: 32768,
                rope_theta: 100000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::DesktopWorkstation,
            },
            Self {
                name: "Stable Diffusion 3.5",
                identifier: "sd-3.5",
                family: ModelFamily::StableDiffusion,
                modality: ModelModality::TextToImage,
                architecture: ModelArchitectureType::DiffusionTransformerDiT,
                default_quantization: QuantizationClass::Fp16Precision,
                total_parameters_billion: 8.1,
                active_parameters_billion: 8.1,
                hidden_dim: 2432,
                intermediate_dim: 9728,
                num_layers: 38,
                num_heads: 38,
                num_kv_heads: 38,
                head_dim: 64,
                vocab_size: 49408,
                max_context_tokens: 512,
                rope_theta: 10000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::DesktopWorkstation,
            },
            Self {
                name: "FLUX.1",
                identifier: "flux.1",
                family: ModelFamily::Flux,
                modality: ModelModality::TextToImage,
                architecture: ModelArchitectureType::DiffusionTransformerDiT,
                default_quantization: QuantizationClass::Bf16Precision,
                total_parameters_billion: 12.0,
                active_parameters_billion: 12.0,
                hidden_dim: 3072,
                intermediate_dim: 12288,
                num_layers: 57,
                num_heads: 24,
                num_kv_heads: 24,
                head_dim: 128,
                vocab_size: 32000,
                max_context_tokens: 512,
                rope_theta: 10000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::DesktopWorkstation,
            },
            Self {
                name: "Wan 2.2 (Video Diffusion)",
                identifier: "wan-2.2",
                family: ModelFamily::Wan,
                modality: ModelModality::TextToVideo,
                architecture: ModelArchitectureType::DiffusionTransformerDiT,
                default_quantization: QuantizationClass::Bf16Precision,
                total_parameters_billion: 14.0,
                active_parameters_billion: 14.0,
                hidden_dim: 5120,
                intermediate_dim: 13824,
                num_layers: 40,
                num_heads: 40,
                num_kv_heads: 40,
                head_dim: 128,
                vocab_size: 32000,
                max_context_tokens: 1024,
                rope_theta: 10000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::EnterpriseRackServer,
            },
            Self {
                name: "HunyuanVideo",
                identifier: "hunyuanvideo",
                family: ModelFamily::HunyuanVideo,
                modality: ModelModality::TextToVideo,
                architecture: ModelArchitectureType::DiffusionTransformerDiT,
                default_quantization: QuantizationClass::Fp8E4M3,
                total_parameters_billion: 13.0,
                active_parameters_billion: 13.0,
                hidden_dim: 4096,
                intermediate_dim: 14336,
                num_layers: 40,
                num_heads: 32,
                num_kv_heads: 32,
                head_dim: 128,
                vocab_size: 32000,
                max_context_tokens: 1024,
                rope_theta: 10000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::EnterpriseRackServer,
            },
            Self {
                name: "Whisper large-v3 (ASR)",
                identifier: "whisper-large-v3",
                family: ModelFamily::Whisper,
                modality: ModelModality::SpeechToTextAsr,
                architecture: ModelArchitectureType::ConvTransformerAsr,
                default_quantization: QuantizationClass::Fp16Precision,
                total_parameters_billion: 1.55,
                active_parameters_billion: 1.55,
                hidden_dim: 1280,
                intermediate_dim: 5120,
                num_layers: 32,
                num_heads: 20,
                num_kv_heads: 20,
                head_dim: 64,
                vocab_size: 51866,
                max_context_tokens: 448,
                rope_theta: 10000.0,
                supports_nvfp4: false,
                optimal_form_factor: HardwareFormFactor::SingleBoardComputerAiHat,
            },
            Self {
                name: "Kokoro (TTS)",
                identifier: "kokoro",
                family: ModelFamily::Kokoro,
                modality: ModelModality::TextToSpeechTts,
                architecture: ModelArchitectureType::NeuralAudioVocoderTts,
                default_quantization: QuantizationClass::Fp16Precision,
                total_parameters_billion: 0.082,
                active_parameters_billion: 0.082,
                hidden_dim: 512,
                intermediate_dim: 2048,
                num_layers: 12,
                num_heads: 8,
                num_kv_heads: 8,
                head_dim: 64,
                vocab_size: 1024,
                max_context_tokens: 512,
                rope_theta: 10000.0,
                supports_nvfp4: false,
                optimal_form_factor: HardwareFormFactor::SingleBoardComputerAiHat,
            },
            Self {
                name: "NVIDIA Nemotron 3 Nano Omni",
                identifier: "nemotron-3-nano-omni",
                family: ModelFamily::NemotronOmni,
                modality: ModelModality::OmniAnyToAny,
                architecture: ModelArchitectureType::MixtureOfExpertsMoe,
                default_quantization: QuantizationClass::Nvfp4Blackwell,
                total_parameters_billion: 30.0,
                active_parameters_billion: 3.0,
                hidden_dim: 3072,
                intermediate_dim: 8192,
                num_layers: 32,
                num_heads: 24,
                num_kv_heads: 8,
                head_dim: 128,
                vocab_size: 152064,
                max_context_tokens: 131072,
                rope_theta: 1000000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::DesktopWorkstation,
            },
            Self {
                name: "Qwen3-Omni",
                identifier: "qwen3-omni",
                family: ModelFamily::QwenOmni,
                modality: ModelModality::OmniAnyToAny,
                architecture: ModelArchitectureType::MixtureOfExpertsMoe,
                default_quantization: QuantizationClass::Nvfp4Blackwell,
                total_parameters_billion: 28.0,
                active_parameters_billion: 3.5,
                hidden_dim: 3072,
                intermediate_dim: 8192,
                num_layers: 32,
                num_heads: 24,
                num_kv_heads: 8,
                head_dim: 128,
                vocab_size: 152064,
                max_context_tokens: 65536,
                rope_theta: 1000000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::DesktopWorkstation,
            },
            // ----------------------------------------------------
            // 3. Specialized & Niche Model Types
            // ----------------------------------------------------
            Self {
                name: "Qwen3-Embedding",
                identifier: "qwen3-embedding",
                family: ModelFamily::QwenEmbedding,
                modality: ModelModality::EmbeddingVector,
                architecture: ModelArchitectureType::DenseTransformer,
                default_quantization: QuantizationClass::GgufQ8_0,
                total_parameters_billion: 0.6,
                active_parameters_billion: 0.6,
                hidden_dim: 1024,
                intermediate_dim: 2816,
                num_layers: 24,
                num_heads: 16,
                num_kv_heads: 16,
                head_dim: 64,
                vocab_size: 152064,
                max_context_tokens: 32768,
                rope_theta: 100000.0,
                supports_nvfp4: false,
                optimal_form_factor: HardwareFormFactor::SingleBoardComputerAiHat,
            },
            Self {
                name: "BGE-M3 (Universal Retrieval)",
                identifier: "bge-m3",
                family: ModelFamily::BgeM3,
                modality: ModelModality::EmbeddingVector,
                architecture: ModelArchitectureType::DenseTransformer,
                default_quantization: QuantizationClass::Fp16Precision,
                total_parameters_billion: 0.57,
                active_parameters_billion: 0.57,
                hidden_dim: 1024,
                intermediate_dim: 4096,
                num_layers: 24,
                num_heads: 16,
                num_kv_heads: 16,
                head_dim: 64,
                vocab_size: 250002,
                max_context_tokens: 8192,
                rope_theta: 10000.0,
                supports_nvfp4: false,
                optimal_form_factor: HardwareFormFactor::SingleBoardComputerAiHat,
            },
            Self {
                name: "NVIDIA Isaac GR00T (Robotics VLA)",
                identifier: "isaac-gr00t",
                family: ModelFamily::IsaacGr00t,
                modality: ModelModality::RoboticsActionVla,
                architecture: ModelArchitectureType::VlaActionTransformer,
                default_quantization: QuantizationClass::Fp16Precision,
                total_parameters_billion: 3.0,
                active_parameters_billion: 3.0,
                hidden_dim: 2560,
                intermediate_dim: 6912,
                num_layers: 32,
                num_heads: 32,
                num_kv_heads: 32,
                head_dim: 80,
                vocab_size: 32000,
                max_context_tokens: 4096,
                rope_theta: 10000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::DesktopWorkstation,
            },
            Self {
                name: "Kairos 3.0 (Edge Robotics World Model)",
                identifier: "kairos-3.0",
                family: ModelFamily::KairosWorldModel,
                modality: ModelModality::WorldModelSimulation,
                architecture: ModelArchitectureType::HybridLinearAttention,
                default_quantization: QuantizationClass::Int8Uniform,
                total_parameters_billion: 4.0,
                active_parameters_billion: 4.0,
                hidden_dim: 3072,
                intermediate_dim: 8192,
                num_layers: 28,
                num_heads: 24,
                num_kv_heads: 24,
                head_dim: 128,
                vocab_size: 32000,
                max_context_tokens: 16384,
                rope_theta: 10000.0,
                supports_nvfp4: false,
                optimal_form_factor: HardwareFormFactor::SingleBoardComputerAiHat,
            },
            Self {
                name: "OpenTSLM (Time Series)",
                identifier: "opentslm",
                family: ModelFamily::OpenTslm,
                modality: ModelModality::TimeSeriesTabular,
                architecture: ModelArchitectureType::DenseTransformer,
                default_quantization: QuantizationClass::Fp16Precision,
                total_parameters_billion: 1.0,
                active_parameters_billion: 1.0,
                hidden_dim: 1536,
                intermediate_dim: 4096,
                num_layers: 24,
                num_heads: 16,
                num_kv_heads: 16,
                head_dim: 96,
                vocab_size: 4096,
                max_context_tokens: 4096,
                rope_theta: 10000.0,
                supports_nvfp4: false,
                optimal_form_factor: HardwareFormFactor::DesktopWorkstation,
            },
            Self {
                name: "ESM (Biological Sequences)",
                identifier: "esm",
                family: ModelFamily::EsmBio,
                modality: ModelModality::ScientificBioMath,
                architecture: ModelArchitectureType::DenseTransformer,
                default_quantization: QuantizationClass::Fp16Precision,
                total_parameters_billion: 3.0,
                active_parameters_billion: 3.0,
                hidden_dim: 2560,
                intermediate_dim: 10240,
                num_layers: 36,
                num_heads: 40,
                num_kv_heads: 40,
                head_dim: 64,
                vocab_size: 33,
                max_context_tokens: 2048,
                rope_theta: 10000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::DesktopWorkstation,
            },
            Self {
                name: "Strands Decider 2B (Agentic Decision)",
                identifier: "strands-decider",
                family: ModelFamily::StrandsDecider,
                modality: ModelModality::DecisionAgentic,
                architecture: ModelArchitectureType::DecisionEngine,
                default_quantization: QuantizationClass::Ptq1_0Ternary,
                total_parameters_billion: 2.0,
                active_parameters_billion: 2.0,
                hidden_dim: 2048,
                intermediate_dim: 5632,
                num_layers: 24,
                num_heads: 16,
                num_kv_heads: 16,
                head_dim: 128,
                vocab_size: 32000,
                max_context_tokens: 8192,
                rope_theta: 10000.0,
                supports_nvfp4: false,
                optimal_form_factor: HardwareFormFactor::SingleBoardComputerAiHat,
            },
            Self {
                name: "TRELLIS (3D Asset Generation)",
                identifier: "trellis",
                family: ModelFamily::Trellis3D,
                modality: ModelModality::Asset3DGeneration,
                architecture: ModelArchitectureType::DiffusionTransformerDiT,
                default_quantization: QuantizationClass::Fp16Precision,
                total_parameters_billion: 4.5,
                active_parameters_billion: 4.5,
                hidden_dim: 2048,
                intermediate_dim: 8192,
                num_layers: 32,
                num_heads: 16,
                num_kv_heads: 16,
                head_dim: 128,
                vocab_size: 32000,
                max_context_tokens: 1024,
                rope_theta: 10000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::DesktopWorkstation,
            },
            Self {
                name: "Kronos (shiyu-coder/Kronos Trading Foundation Model)",
                identifier: "kronos",
                family: ModelFamily::KronosTrading,
                modality: ModelModality::FinancialTradingTimeSeries,
                architecture: ModelArchitectureType::FinancialCausalTransformer,
                default_quantization: QuantizationClass::Fp16Precision,
                total_parameters_billion: 1.5,
                active_parameters_billion: 1.5,
                hidden_dim: 2048,
                intermediate_dim: 5632,
                num_layers: 24,
                num_heads: 16,
                num_kv_heads: 16,
                head_dim: 128,
                vocab_size: 8192, // Financial token discrete bins
                max_context_tokens: 8192,
                rope_theta: 10000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::DesktopWorkstation,
            },
            Self {
                name: "Kronos-3B (shiyu-coder/Kronos-3B Quantitative HFT)",
                identifier: "kronos-3b",
                family: ModelFamily::KronosTrading,
                modality: ModelModality::FinancialTradingTimeSeries,
                architecture: ModelArchitectureType::FinancialCausalTransformer,
                default_quantization: QuantizationClass::Fp16Precision,
                total_parameters_billion: 3.2,
                active_parameters_billion: 3.2,
                hidden_dim: 3072,
                intermediate_dim: 8192,
                num_layers: 32,
                num_heads: 24,
                num_kv_heads: 8,
                head_dim: 128,
                vocab_size: 8192,
                max_context_tokens: 16384,
                rope_theta: 10000.0,
                supports_nvfp4: true,
                optimal_form_factor: HardwareFormFactor::DesktopWorkstation,
            },
        ]
    }
}
